== RISC-V Tests
https://github.com/riscv-software-src/riscv-tests[RISC-V Tests]
はRISC-Vの検証用のテストベンチ集です.
作ったプロセッサがRISC-Vの仕様を満たしているか検証できます．

=== Build
RISC-V Testsはプロセッサ毎にビルドする必要があります．
https://github.com/riscv-software-src/riscv-tests[GitHub]
で公開されているのでクローンしてきます．

```
$ git clone https://github.com/riscv-software-src/riscv-tests
$ cd riscv-tests
$ git submodule update --init --recursive
$ autoconf
$ ./configure --with-xlen=32
```

ここでは，RV32I向けにRISC-V Testsを修正する方法を説明します．

==== riscv-tests/isa/Makefile
RV32Iで必要なテストは， `rv32ui` です．
`riscv-tests/isa/Makefile` で次を変更します．

```
42|    default: rv32ui
```

==== riscv-tests/env/p/link.ld
ハードウェア固有のメモリマップを定義するリンカです．
今回は命令メモリとデータメモリが統合されたメモリ( `ram` )を考えます．
```
OUTPUT_ARCH("riscv")
ENTRY(_start)

MEMORY {
    ram : ORIGIN = 0x00000000, LENGTH = 0x00001000
}

SECTIONS
{
  .text.init : { *(.text.init) } > ram
  .text : { *(.text) } > ram
  .data : { *(.data) } > ram
  .bss : { *(.bss) } > ram
  _end = .;
}
```

==== riscv-tests/env/p/riscv-test.h
このヘッダに初期化ルーチンを記述します．
ですので，RISC-V Testsでは `crt0.S` は不要です．
すべてのテストは `RVTEST_CODE_BEGIN` から実行されます．
```
183|    #define RVTEST_CODE_BEGIN        \
```
デフォルトの初期化ルーチンでは `Zicsr` 拡張や例外処理をサポートしていないと使えない命令が使用されているので，
RV32I用に修正していきます．
`_start:` が1番最初に実行される命令です．
いろいろ書いてありますが，XREGの初期化以外不要です．
全部削除します．
```
#define RVTEST_CODE_BEGIN           \
        .section .text.init;        \
        .globl _start;              \
_start:                             \
        INIT_XREG;
```

`RVTEST_PASS` と `RVTEST_FAIL` は
テストに通ったときと落ちたときの処理を定義します．
例外処理をサポートしないプロセッサでは
`fence` や `ecall` は使えないので，別のルーチンに変更します．
今回は， プロセッサが `0x40008000` に `777` を書き込んだらPASS,
`0` を書き込んだらFAILという約束にします．
実装は次のようになります．
```
#define RVTEST_PASS                                                     \
        lui t0, 0x40008;                                                \
        li t1, 777;                                                     \
        sw t1, 0(t0);                                                   \
1:      j 1b;                                                           
```

```
#define RVTEST_FAIL                                                     \
        lui t0, 0x40008;                                                \
        li t1, 0;                                                       \
        sw t1, 0(t0);                                                   \
1:      j 1b;                                                           
```
`tohost` はホストへデータを送信するアドレスを指定します．
一般的にはUARTのアドレスを指定します．
今回は `tohost` は `0x40008000` ですが，先ほどの `RVTEST_PASS` と `RVTEST_FAIL`
で決め打ちしたので，今回は使いません．ですので削除します．
```
#define RVTEST_DATA_BEGIN                                               \
        EXTRA_DATA                                                      \
        .align 4; .global begin_signature; begin_signature:
```
[TIP]
====
使用する場合は，リンカに
```
. = 0x40008000
.tohost : { *(.tohost) }
```
のように記述します．
====


`umimp` は例外処理をサポートしないプロセッサでは意味がないので，削除します．
```
#define RVTEST_CODE_END 
```

以上の変更でもって，
次のコマンドでテストベンチを生成します．
```
$ make isa
```

`riscv-tests/isa` にオブジェクトダンプと実行可能ファイルが生成されます．
ここで， `rv32ui-p-` と `rv32ui-v-` が生成されていると思います．
`rv32ui-v-` は仮想アドレスをサポートするプロセッサ向けのテストです．
今回はサポートしない方針なので，`rv32ui-p-` のみを使用します．
ここでは， `tests` ディレクトリにコピーします．
```
$ mkdir tests
$ cp riscv-tests/isa/rv32ui-p-* tests/
```

=== Usage
実行可能ファイルは用意できたので，Verilogのシミュレーションで使える形に変換します．
変換には `objcopy` を使うことができます．
`hex` がこの実装です．
`-O verilog` で `$readmemh` で読み取れる形式のファイルを生成できます．

```
hex: tests
	for elf in $(wildcard tests/*.elf); do \
		riscv32-unknown-elf-objcopy -O verilog \ 
        $$elf tests/$$(basename $$elf .elf).hex; \
	done
```

[NOTE]
====
今回はバイトアライメントされたメモリを想定しています．
ワードアライメントの場合は次の方法を使う方が確実です．
```
$ riscv32-unknown-elf-objcopy -O binary main.elf main.bin
$ dd if=main.bin of=mem.bin conv=sync bs=1KB
$ hexdump -v -e '1/4 "%08x\n"' main.bin > main.hex
```
====


テストベンチは次のように記述できるかと思います．
```
module top;
    reg clk = 1; initial forever #5 clk = ~clk; // 100MHz clock
    reg [63:0] cc = 0; always @(posedge clk) cc <= cc+1; // clock cycle counter

    string hex_file;
    initial begin
        if ($value$plusargs("hex_file=%s", hex_file)) begin
            $display("Loading hex file: %s", hex_file);
            $readmemh(hex_file, top.dut.ram);
        end else begin
            $display("No hex file specified, using default values.");
        end
    end

    reg done = 0;
    always @(posedge clk) begin
        if (top.dut.dbus_en == 4'b1111 && top.dut.dbus_write_addr == 32'h40008000) begin
            if (top.dut.dbus_write_data == 777) $finish;
            else $fatal;
        end
        else if (cc == 1000) $fatal;
    end

    main dut(
        .clk_i(clk),
        .rx_i(1'b1),
        .tx_o()
    );
endmodule
```

検証は次のようなルールで自動化してしまうのが，楽です．
```
valid: 
	@for file in $(wildcard tests/*.hex); do \
		if ! ./obj_dir/Vtop +hex_file=$$file > /dev/null; then \
			echo "\033[31m[FAIL] $$file\033[0m"; \
		else \
			echo "\033[32m[PASS] $$file\033[0m"; \
		fi; \
	done
```

[NOTE]
====
通らなくていいテストがあります．
それが，`ma_data` と `fance_i` です．
`ma_data` はミスアライメントを検証するテストです．
例えば， `0x01` に対して `lw` するようなケースが検証されます．
このアライメントはRISC-V ISAの必須要件ではないので，サポートしない方針なら無視できます．
`fence_i` は命令メモリを書き換えた際のハザードをチェックします．
命令メモリをROMとして実装する場合は，通らなくてOKです．
====
