== RISC-V GNU Toolchain
https://github.com/riscv-collab/riscv-gnu-toolchain[RISC-V GNU Toolchain]は
RISC-Vのクロスコンパイラです．

=== Build
ビルド方法を説明します．

[NOTE]
====
研究室のサーバーを利用する場合は `/tools/cad/riscv/rv32ima` にあるので，ビルドする必要はありません．
====

ソースコードは
https://github.com/riscv-non-isa/tg-nexus-trace[GitHub]
で公開されています．
```
$ git clone https://github.com/riscv/riscv-gnu-toolchain
```

configureで使いたいRISC-VのアーキテクチャとABIを選択します．
例えば，RV32IMを使用したい場合は次のようなオプションを指定します．
```
--with-arch=rv32im --with-abi=ilp32
```
[TIP]
====
LINUXを動作させるようなプロセッサを使用する場合は，
```
--with-arch=rv32ima_Zicsr_Zifencei_Zicntr --with-abi=ilp32
```
を使用します．
====

記述全体は次のようになります．
```
$ ./configure --prefix=/home/fujino/rv32im --with-arch=rv32im --with-abi=ilp32
$ make -j $(nproc)
```
だいたい，5分から10分程度で終わります．
ビルドが完了すると `/home/fujino/rv32im/bin` に
`riscv32-unknown-elf-` から始まるコンパイラが生成されています．

[WARNING]
====
`j` オプションを使うとエラーを見落とすことがあります．
`riscv32-unknown-elf-g++` がないとかライブラリが見つからないなどの問題があったら，
失敗しています．
この場合は，シングルスレッドで実行してみてください．
時間はかかりますが，確実です．
====

=== Useage
使い方はx86のgccとあまり変わらないです．
<<gcc>>を次にまとめました．

[[gcc]]
.よく使うオプション
[cols="2*", options="header"]
|====
|Option
|Describe

|-march
|生成する命令セットを指定します． 
アーキテクチャが `RV32IMA_Zicsr` の場合， `-march=rv32ima_zicsr` のように指定します．

|-mabi
|ABIを指定します． `-mabi=ilp32` 以外使うことはないかと思います．

|-nostartfiles
|エントリーポイント `_start` をユーザー定義のものに変更します．
このオプションなしで，初期化ルーチンをリンクすると，標準ライブラリの `_start` と衝突します．

|-O
|最適化オプションです． `-Os` か `-O2` を使うことが多いです．

|-T
|リンカを指定します． `-Tsrc/link.ld` のように使います．
|====

CFU Proving Groundでは次のようにコンパイルしています．
```
$ riscv32-unknown-elf-gcc -Os -march=rv32im -mabi=ilp32 -nostartfiles -Iapp -Tapp/link.ld -o build/main.elf app/crt0.s app/*.c *.c 
```
[cols="2*", options="header"]
|====
|Option
|Describe

|-Os
|生成する実行可能ファイルのサイズを最小化する方向に最適化します．

|-march=rv32im
|RVProcがサポートするISAはRV32IMです．

|-nostartfiles
|RVProcは `crt0.s` から命令を実行したいので，GCC標準のスタートアップルーチンを生成しないオプションです．
このオプションを使用する場合は，リンカに `_start` というエントリを教える必要があります．
RVProcはこれを，`crt0.s` で行っています．

|-Iapp
|インクルードするヘッダーを `./app` ディレクトリから探してくれというオプションです．

|-Tapp/link.ld
|リンカを指定します．ここでは `./app/link.ld` を指定しています．

|-o build/main.elf
|出力先を指定します．
|====

